mode: auto

avatar:
  url: /images/avatar.jpg
  status:
    enable: true
    emoji: ğŸ˜­
    message: å¥½å¤šä½œä¸š

banner:
  enable: true
  title: æ€é¥æ–¹çš„å°å®¶
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

notice:
  enable: true
  content: åˆšå»ºå¥½è¿˜æ²¡ä»€ä¹ˆå†…å®¹ï¼Œä½ å…ˆåˆ«æ€¥ï¼

reward:
  enable: true
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
  methods:
    - name: æ”¯ä»˜å®
      path: /images/donate/alipay-qrcode.png
      color: '#00A3EE'
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      path: /images/donate/qq-qrcode.png
      color: '#12B7F5'
      icon: ri:qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: /images/donate/wechat-qrcode.png
      color: '#2DC100'
      icon: ri:wechat-pay-line

bg_image:
  enable: false

engine_search:
  enable: true
  href: 'https://www.bing.com/search?q=site:'
  domain: seayay.icu

trianglify:
  enable: true
  cellSize: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

fireworks:
  enable: true
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'

comment:
  candidates:
    - waline
    # - giscus
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://github.com/Seayay/seayay.github.io/discussions" target="_blank">GitHub Discussions</a> ä¸æˆ‘äº¤æµã€‚

waline:
  enable: false
  serverURL: https://seayay-waline.vercel.app
  visitor: true
  comment: true
  emoji:
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: [nick]

github_issues:
  enable: false

github_discussions:
  enable: true
  username: Seayay
  repository: seayay.github.io

footer:
  since: 2022
  icon:
    url: https://afdian.net/a/Seayay
    title: æ€é¥æ–¹çš„çˆ±å‘ç”µ
  powered:
    enable: version

google_analytics:
  enable: true
  id: G-5VCKPEK8E4

google_adsense:
  enable: false
  client: ca-pub-5138150202544751

post_edit:
  enable: true
  url: https://github.com/Seayay/seayay.github.io/tree/main/source/

albums:
  enable: true

girls:
  enable: true

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue

menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: ri:clipboard-line

cursor:
  enable: true

baidu_push: true

google_tagmanager:
  enable: false
  id: 

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  - name: GitHub
    link: https://github.com/Seayay
    icon: ri:github-line
    color: '#6e5494'
  - name: å¾®åš
    link: https://weibo.com/seayay
    icon: ri:weibo-line
    color: '#E6162D'
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=3811517250
    icon: ri:netease-cloud-music-line
    color: '#C20C0C'
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/54907459
    icon: ri:bilibili-line
    color: '#FF8EB3'
  - name: Twitter
    link: https://twitter.com/Seayay2
    icon: ri:twitter-line
    color: '#1da1f2'
  # - name: Telegram
  #   link: 
  #   icon: ri:telegram-line
  #   color: "#0088CC"
  # - name: Telegram Channel
  #   link: 
  #   icon: ri:telegram-line
  #   color: '#0088CC'
  # - name: Discord
  #   link: https://discord.gg/nd3mPkU5j8
  #   icon: ri:discord-line
  #   color: '#5A6DE2'
  - name: E-Mail
    link: mailto:seayay@seayay.icu
    icon: ri:mail-line
    color: '#8E71C1'

wordcount:
  enable: true
  count: true
  time: true

pjax:
  enable: true

mourn:
  enable: true
  days:
    - 4-4

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

medium_zoom: true
